version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xmx2g
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  #kafka and zookeeper
  zookeper:
    container_name: go-zookeeper
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT:2181
    ports:
      - 2181:2181
  kafka:
    container_name: go-kafka
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT:zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS:PLAINTEXT://localhost:29092
    ports:
      - 29091:29091

networks:
  es-net:
    driver: bridge

